In [1]:
import pandas as pd

In [5]:
%pwd

'c:\\Users\\luzinsan\\Desktop\\Innopolis\\assig2'

In [13]:
compaigns = pd.read_csv('./campaigns.csv')

In [23]:
compaigns

,id,campaign_type,channel,topic,started_at,finished_at,total_count,ab_test,warmup_mode,hour_limit,subject_length,subject_with_personalization,subject_with_deadline,subject_with_emoji,subject_with_bonuses,subject_with_discount,subject_with_saleout,is_test,position
0,63,bulk,mobile_push,sale out,2021-04-30 07:22:36.615023,2021-04-30 07:23:41,48211.0,NaN,False,NaN,146.0,False,False,True,False,False,False,NaN,NaN
1,64,bulk,mobile_push,sale out,2021-04-30 09:02:50.817227,2021-04-30 09:04:08,1037337.0,NaN,False,NaN,97.0,False,False,True,False,False,False,NaN,NaN
2,78,bulk,mobile_push,sale out,2021-05-06 07:14:10.533318,2021-05-06 07:15:17,70080.0,NaN,False,NaN,146.0,False,False,True,False,False,False,NaN,NaN
3,79,bulk,mobile_push,sale out,2021-05-06 09:03:56.486750,2021-05-06 09:42:15,921838.0,NaN,False,NaN,97.0,False,False,True,False,False,False,NaN,NaN
4,89,bulk,mobile_push,NaN,2021-05-07 11:54:06.168664,2021-05-07 11:54:38,45503.0,NaN,False,NaN,109.0,False,True,True,False,False,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1902,179,transactional,email,profile updated,NaN,NaN,NaN,NaN,NaN,NaN,134.0,False,False,False,False,False,False,NaN,NaN
1903,35,transactional,email,order reminder,NaN,NaN,NaN,NaN,NaN,NaN,88.0,False,False,False,False,False,False,NaN,NaN
1904,57,transactional,email,order reminder,NaN,NaN,NaN,NaN,NaN,NaN,88.0,False,False,False,False,False,False,NaN,NaN
1905,56,transactional,email,order reminder,NaN,NaN,NaN,NaN,NaN,NaN,88.0,False,False,False,False,False,False,NaN,NaN
1906,237,transactional,email,wish list status,NaN,NaN,NaN,NaN,NaN,NaN,104.0,False,False,True,False,False,False,NaN,NaN

In [24]:
import numpy as np

In [36]:
print(compaigns.value_counts('channel'))

compaigns.value_counts('campaign_type')

channel
mobile_push     1396
email            483
multichannel      27
sms                1
dtype: int64

campaign_type
bulk             1830
transactional      50
trigger            27
dtype: int64

In [59]:
print(compaigns[compaigns['topic'].notna()].value_counts('channel'))

compaigns[compaigns['topic'].notna()].value_counts('campaign_type')

channel
mobile_push     1382
email            470
multichannel      24
sms                1
dtype: int64

campaign_type
bulk             1804
transactional      49
trigger            24
dtype: int64

In [43]:
compaigns[compaigns['campaign_type']!='bulk']['finished_at'].notna().sum()

0

In [47]:
compaigns[compaigns['campaign_type']!='bulk']['total_count'].notna().sum()

0

In [53]:
compaigns[compaigns['campaign_type']=='transactional']['is_test'].notna().sum()

0

In [57]:
compaigns[compaigns['campaign_type']!='trigger']['position'].notna().sum()

0

In [63]:
compaigns[compaigns['campaign_type']=='multichannel']['subject_length'].notna().sum()

0

In [2]:
messages = pd.read_csv('messages.csv')

C:\Users\luzinsan\AppData\Local\Temp\ipykernel_35452\1032502617.py:1: DtypeWarning: Columns (7,8,16,17,21,23,25,27,29) have mixed types. Specify dtype option on import or set low_memory=False.
  messages = pd.read_csv('messages.csv')

In [10]:
messages

,id,message_id,campaign_id,message_type,client_id,channel,category,platform,email_provider,stream,...,is_complained,complained_at,is_blocked,blocked_at,is_purchased,purchased_at,created_at,updated_at,user_device_id,user_id
0,3533908,b7d6772d-8989-4abe-b14f-da8935fb7482,179,transactional,1515915625487629506,email,NaN,NaN,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,2023-04-27 08:55:15.526907,2023-04-27 09:00:45.678375,6,548762950
1,3520988,05f889ef-98ed-4eee-acb6-de4f30be4837,27,transactional,1515915625594602211,email,NaN,NaN,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,2023-04-27 08:54:56.567977,2023-04-27 08:55:18.969367,1,559460221
2,3521097,0ce3deaf-1773-46ed-88a9-90ea1dcb1fdc,27,transactional,1515915625505234697,email,NaN,NaN,gmail.com,desktop,...,f,NaN,f,NaN,f,NaN,2023-04-27 08:54:56.768951,2023-04-27 08:54:56.769921,7,550523469
3,3521249,1692346e-2c6d-427d-9b08-d10cf081a561,27,transactional,1515915625472683606,email,NaN,NaN,gmail.com,desktop,...,f,NaN,f,NaN,f,NaN,2023-04-27 08:54:56.993038,2023-04-27 08:54:56.99424,6,547268360
4,3521284,18f7050c-96a4-4f68-921d-1dbbd7929f5a,27,transactional,1515915625500988431,email,NaN,NaN,yandex.ru,desktop,...,f,NaN,f,NaN,f,NaN,2023-04-27 08:54:57.045129,2023-04-27 08:55:19.296068,1,550098843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3000739,20161140,8f28c87f-2b42-4ff1-b933-6b55498a6021,18212,trigger,1515915625473100462,email,NaN,NaN,yandex.ru,desktop,...,f,NaN,f,NaN,f,NaN,2023-04-27 20:35:41.651567,2023-04-27 20:35:41.652511,2,547310046
3000740,20161163,1f0a9292-5e6f-44e6-9192-a9fdb04eb163,18223,trigger,1515915625473147877,email,NaN,NaN,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,2023-04-27 20:35:41.684036,2023-04-27 20:35:41.684583,7,547314787
3000741,20161164,e8149feb-838c-4405-a94f-8ca46becf006,18212,trigger,1515915625473147877,email,NaN,NaN,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,2023-04-27 20:35:41.68529,2023-04-27 20:35:41.685915,7,547314787
3000742,20161169,6c1f03d9-ec9c-47b5-9706-a7347fbef872,18212,trigger,1515915625473164433,email,NaN,desktop,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,2023-04-27 20:35:41.693284,2023-04-27 20:35:41.694484,3,547316443
3000743,20161252,7d0dbb29-ef70-43b0-b6ed-e39414f7b071,18212,trigger,1515915625473415016,email,NaN,desktop,mail.ru,desktop,...,f,NaN,f,NaN,f,NaN,2023-04-27 20:35:41.80899,2023-04-27 21:52:26.699651,6,547341501

In [13]:
behavior_cols = ['is_complained', 'is_blocked','is_purchased','is_opened','is_clicked', 'is_unsubscribed', 'is_hard_bounced','is_soft_bounced']

In [11]:
ununique_idx = messages[behavior_cols].apply(lambda x :x.map({'t':True, 'f':False})).sum(1) > 1
ununique_idx

0          False
1          False
2          False
3          False
4          False
           ...
3000739    False
3000740    False
3000741    False
3000742    False
3000743    False
Length: 3000744, dtype: bool

In [26]:
messages[ununique_idx][behavior_cols].head()

,is_complained,is_blocked,is_purchased,is_opened,is_clicked,is_unsubscribed,is_hard_bounced,is_soft_bounced
11,f,f,f,t,t,f,f,f
19,f,f,f,t,t,f,f,f
22,f,f,f,t,t,f,f,f
46,f,f,f,t,t,f,f,f
57,f,f,t,t,t,f,f,f

In [62]:
msg_with_email = messages.dropna(subset=['email_provider'])[:1000000]
nonunique_emails_idx = msg_with_email.groupby('client_id')['email_provider'].agg('nunique') > 1
nonunique_emails_idx[nonunique_emails_idx.values]

client_id
1515915625536249762    True
1515915625558170533    True
1515915625579453478    True
1515915625585491451    True
1515915625630392856    True
1515915625637875231    True
1515915625637977930    True
1515915625637979618    True
1515915625637979636    True
1515915625639014777    True
1515915625640701487    True
1515915625640702484    True
1515915625641407508    True
1515915625641586793    True
1515915625641598469    True
1515915625643532489    True
Name: email_provider, dtype: bool

In [64]:
msg_with_provider = messages.dropna(subset=['stream'])[:]
nonunique_provider_idx = msg_with_provider.groupby('client_id')['stream'].agg('nunique') > 1
nonunique_provider_idx[nonunique_provider_idx.values]

Series([], Name: stream, dtype: bool)

In [65]:
msg_with_platform = messages.dropna(subset=['platform'])[:10000]
nonunique_platform_idx = msg_with_platform.groupby('client_id')['platform'].agg('nunique') > 1
nonunique_platform_idx[nonunique_platform_idx.values]

client_id
1515915625468061170    True
1515915625468091141    True
1515915625468098184    True
1515915625468126443    True
1515915625468134232    True
                       ...
1515915625637491699    True
1515915625637791669    True
1515915625638723201    True
1515915625639453531    True
1515915625643219766    True
Name: platform, Length: 233, dtype: bool

In [72]:
messages['category'].notna().sum()

0

In [73]:
messages['message_type']

0          transactional
1          transactional
2          transactional
3          transactional
4          transactional
               ...
3000739          trigger
3000740          trigger
3000741          trigger
3000742          trigger
3000743          trigger
Name: message_type, Length: 3000744, dtype: object